Repository microservices/openmicroservices.org, pull requests merged in 2019-10, with the labels that each got.

#121 feat: improvements
  .vuepress/components/Docs.vue
  .vuepress/components/Home.vue
  .vuepress/components/pages/home/OMGSpec.vue
  .vuepress/components/shared/Computer.vue
  .vuepress/components/shared/Contact.vue
  .vuepress/components/shared/NavLinks.vue
  .vuepress/components/shared/Navbar.vue
  .vuepress/public/assets/img/illustrations/app.svg
  .vuepress/public/assets/img/illustrations/services.svg
  .vuepress/styles/index.styl
  cli/overview/README.md
  cli/test/README.md
  cli/validate/README.md
  examples/http/README.md
  interoperability/openapi/README.md
  introduction/anatomy/README.md
  introduction/comparisons/openapi/README.md
  introduction/overview/README.md
  readme.md
  schema/actions/README.md
  schema/environment/README.md
  schema/events/README.md
  schema/forwards/README.md
  schema/health/README.md
  schema/info/README.md
  schema/interface/README.md
  schema/lifecycle/README.md
  schema/logs/README.md
  schema/metrics/README.md
  schema/volumes/README.md
Labels: enhancement 🚀

#160 docs(cli): update cli usage docs
  .nvmrc
  .vuepress/components/util.js
  .vuepress/config.js
  .vuepress/styles/index.styl
  cli/build/README.md
  cli/list/README.md
  cli/run/README.md
  cli/subscribe/README.md
  cli/test/README.md
  cli/ui/README.md
  cli/validate/README.md
Labels: documentation 📚

#164 fix(badges): replace custom badge component with native badge component
  app/schema/interface/README.md
Labels: help wanted 👀
